name: hako
description: "A state management library for Flutter designed for simplicity, performance, and testability."
version: 0.0.3
repository: https://github.com/parsodyl/hako
issue_tracker: https://github.com/parsodyl/hako/issues

topics:
  - state-management
  - provider
  - hako

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  provider: ^6.1.5

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
